apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: loka

resources:
  - namespace.yaml
  - configmap.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - hpa.yaml

commonLabels:
  app.kubernetes.io/name: loka
  app.kubernetes.io/version: "0.1.0"
  app.kubernetes.io/managed-by: kustomize

images:
  - name: loka
    newTag: latest
